// Generated by scripts/sync-curriculum.mjs. Do not edit by hand.
export type CurriculumLevel = "middle" | "high";

export type CurriculumCourse = {
  id: string;
  level: CurriculumLevel;
  subjectGroup: string;
  name: string;
  category: string;
  topics: string[];
};

export const CURRICULUM_SOURCE = {
  "repository": "https://github.com/DECK6/korean-secondary-learning-map",
  "commit": "68e62283cfc337e2de643a3cd1b0334e411acf54",
  "releases": {
    "middle": "kr-2022-middle-v0.5.0-candidate",
    "high": "kr-2022-high-v0.5.0-candidate"
  }
} as const;

export const CURRICULUM_COURSES: CurriculumCourse[] = [
  {
    "id": "kr.course.2022.high.c57a4fefb53c582d",
    "level": "high",
    "subjectGroup": "과학",
    "name": "과학의 역사와 문화",
    "category": "융합 선택",
    "topics": [
      "과학과 문명의 탄생과 통합",
      "과학과 인류의 미래",
      "변화하는 과학과 세계"
    ]
  },
  {
    "id": "kr.course.2022.high.405980f16b59bcfe",
    "level": "high",
    "subjectGroup": "과학",
    "name": "과학탐구실험1",
    "category": "공통",
    "topics": [
      "과학 탐구의 과정과 절차",
      "과학의 본성과 역사 속의 과학 탐구"
    ]
  },
  {
    "id": "kr.course.2022.high.650024939bd22742",
    "level": "high",
    "subjectGroup": "과학",
    "name": "과학탐구실험2",
    "category": "공통",
    "topics": [
      "미래 사회와 첨단 과학 탐구",
      "생활 속의 과학 탐구"
    ]
  },
  {
    "id": "kr.course.2022.high.35811985f46abf91",
    "level": "high",
    "subjectGroup": "과학",
    "name": "기후변화와 환경생태",
    "category": "융합 선택",
    "topics": [
      "기후와 환경생태의 특성",
      "기후위기에 대응하는 우리의 노력",
      "기후위기와 환경생태 변화"
    ]
  },
  {
    "id": "kr.course.2022.high.a3e0712414844bb3",
    "level": "high",
    "subjectGroup": "과학",
    "name": "물리학",
    "category": "일반 선택",
    "topics": [
      "빛과 물질",
      "전기와 자기",
      "힘과 에너지"
    ]
  },
  {
    "id": "kr.course.2022.high.ccdce9a9cbfbe8be",
    "level": "high",
    "subjectGroup": "과학",
    "name": "물질과 에너지",
    "category": "진로 선택",
    "topics": [
      "물질의 세 가지 상태",
      "반응 속도",
      "용액의 성질",
      "화학 변화의 자발성"
    ]
  },
  {
    "id": "kr.course.2022.high.e4000a151f61fc2d",
    "level": "high",
    "subjectGroup": "과학",
    "name": "생명과학",
    "category": "일반 선택",
    "topics": [
      "생명 시스템의 구성",
      "생명의 연속성과 다양성",
      "항상성과 몸의 조절"
    ]
  },
  {
    "id": "kr.course.2022.high.92ec69a3474b6737",
    "level": "high",
    "subjectGroup": "과학",
    "name": "생물의 유전",
    "category": "진로 선택",
    "topics": [
      "생명공학기술",
      "유전자와 유전물질",
      "유전자의 발현"
    ]
  },
  {
    "id": "kr.course.2022.high.9259e0722898177b",
    "level": "high",
    "subjectGroup": "과학",
    "name": "세포와 물질대사",
    "category": "진로 선택",
    "topics": [
      "물질대사와 에너지",
      "세포",
      "세포호흡과 광합성"
    ]
  },
  {
    "id": "kr.course.2022.high.4c5c974f5e3449db",
    "level": "high",
    "subjectGroup": "과학",
    "name": "역학과 에너지",
    "category": "진로 선택",
    "topics": [
      "시공간과 운동",
      "열과 에너지",
      "탄성파와 소리"
    ]
  },
  {
    "id": "kr.course.2022.high.adc674b93d6653ed",
    "level": "high",
    "subjectGroup": "과학",
    "name": "융합과학 탐구",
    "category": "융합 선택",
    "topics": [
      "융합과학 탐구의 과정",
      "융합과학 탐구의 이해",
      "융합과학 탐구의 전망"
    ]
  },
  {
    "id": "kr.course.2022.high.47cd1defd30f5bd7",
    "level": "high",
    "subjectGroup": "과학",
    "name": "전자기와 양자",
    "category": "진로 선택",
    "topics": [
      "빛과 정보 통신",
      "양자와 미시세계",
      "전자기적 상호작용"
    ]
  },
  {
    "id": "kr.course.2022.high.9587081f2a5eebb2",
    "level": "high",
    "subjectGroup": "과학",
    "name": "지구과학",
    "category": "일반 선택",
    "topics": [
      "대기와 해양의 상호작용",
      "지구의 역사와 한반도의 암석",
      "태양계 천체와 별과 우주의 진화"
    ]
  },
  {
    "id": "kr.course.2022.high.8a1581742b2c86f6",
    "level": "high",
    "subjectGroup": "과학",
    "name": "지구시스템과학",
    "category": "진로 선택",
    "topics": [
      "강수 과정과 대기의 운동",
      "지구 탄생과 생동하는 지구",
      "해수의 운동"
    ]
  },
  {
    "id": "kr.course.2022.high.997f40d6e251b180",
    "level": "high",
    "subjectGroup": "과학",
    "name": "통합과학1",
    "category": "공통",
    "topics": [
      "과학의 기초",
      "물질과 규칙성",
      "시스템과 상호작용"
    ]
  },
  {
    "id": "kr.course.2022.high.3e1de9b39f3e77e3",
    "level": "high",
    "subjectGroup": "과학",
    "name": "통합과학2",
    "category": "공통",
    "topics": [
      "과학과 미래 사회",
      "변화와 다양성",
      "환경과 에너지"
    ]
  },
  {
    "id": "kr.course.2022.high.e56e90f718cb34b9",
    "level": "high",
    "subjectGroup": "과학",
    "name": "행성우주과학",
    "category": "진로 선택",
    "topics": [
      "우주탐사와 행성계",
      "은하와 우주",
      "태양과 별의 관측"
    ]
  },
  {
    "id": "kr.course.2022.high.a9a3a9a36115d467",
    "level": "high",
    "subjectGroup": "과학",
    "name": "화학",
    "category": "일반 선택",
    "topics": [
      "물질의 구조와 성질",
      "역동적인 화학 반응",
      "화학 평형",
      "화학의 언어"
    ]
  },
  {
    "id": "kr.course.2022.high.bbb3fc715f09a9f1",
    "level": "high",
    "subjectGroup": "과학",
    "name": "화학 반응의 세계",
    "category": "진로 선택",
    "topics": [
      "산 염기 평형",
      "산화⋅환원 반응",
      "탄소 화합물과 반응"
    ]
  },
  {
    "id": "kr.course.2022.high.5aacb02a6fbc60f1",
    "level": "high",
    "subjectGroup": "과학 계열",
    "name": "고급 기하",
    "category": "진로 선택",
    "topics": [
      "곡면의 성질",
      "곡선의 성질",
      "작도와 평면기하"
    ]
  },
  {
    "id": "kr.course.2022.high.9395eaed9e189893",
    "level": "high",
    "subjectGroup": "과학 계열",
    "name": "고급 대수",
    "category": "진로 선택",
    "topics": [
      "벡터공간",
      "행렬과 선형변환",
      "행렬의 대각화"
    ]
  },
  {
    "id": "kr.course.2022.high.fe078b9bf3360f43",
    "level": "high",
    "subjectGroup": "과학 계열",
    "name": "고급 물리학",
    "category": "진로 선택",
    "topics": [
      "광학",
      "역학",
      "전자기학",
      "현대 물리"
    ]
  },
  {
    "id": "kr.course.2022.high.5c896c9748b34519",
    "level": "high",
    "subjectGroup": "과학 계열",
    "name": "고급 미적분",
    "category": "진로 선택",
    "topics": [
      "극좌표와 극곡선",
      "급수",
      "미분방정식",
      "미적분의 활용"
    ]
  },
  {
    "id": "kr.course.2022.high.d20d1c5249072f2f",
    "level": "high",
    "subjectGroup": "과학 계열",
    "name": "고급 생명과학",
    "category": "진로 선택",
    "topics": [
      "생명공학기술과 미래",
      "생명의 연속성",
      "생물의 구조와 에너지",
      "생물의 조절과 방어"
    ]
  },
  {
    "id": "kr.course.2022.high.bbf6258b8c74458e",
    "level": "high",
    "subjectGroup": "과학 계열",
    "name": "고급 지구과학",
    "category": "진로 선택",
    "topics": [
      "고체 지구",
      "대기와 해양",
      "우주"
    ]
  },
  {
    "id": "kr.course.2022.high.706bf7c1454169b3",
    "level": "high",
    "subjectGroup": "과학 계열",
    "name": "고급 화학",
    "category": "진로 선택",
    "topics": [
      "물질의 구조",
      "물질의 변화와 에너지",
      "물질의 변화와 화학 평형",
      "물질의 성질"
    ]
  },
  {
    "id": "kr.course.2022.high.807092d6486c740f",
    "level": "high",
    "subjectGroup": "과학 계열",
    "name": "과학과제 연구",
    "category": "진로 선택",
    "topics": [
      "과학 연구의 결론 도출 및 공유",
      "과학 연구의 문제 탐색 및 선정",
      "과학 연구의 설계 및 수행"
    ]
  },
  {
    "id": "kr.course.2022.high.3e0c36e1e3ce0728",
    "level": "high",
    "subjectGroup": "과학 계열",
    "name": "물리학 실험",
    "category": "융합 선택",
    "topics": [
      "광학",
      "물리 실험의 기초",
      "역학",
      "전자기학",
      "현대 물리"
    ]
  },
  {
    "id": "kr.course.2022.high.702213fc0dd545f9",
    "level": "high",
    "subjectGroup": "과학 계열",
    "name": "생명과학 실험",
    "category": "융합 선택",
    "topics": [
      "생명공학",
      "생명의 연속성과 다양성",
      "생물의 구조와 에너지",
      "자극과 반응",
      "환경과 생태계"
    ]
  },
  {
    "id": "kr.course.2022.high.eb1d2dde90320a58",
    "level": "high",
    "subjectGroup": "과학 계열",
    "name": "이산 수학",
    "category": "진로 선택",
    "topics": [
      "그래프",
      "선택과 배열",
      "수의 표현과 부울 대수",
      "점화 관계와 알고리즘"
    ]
  },
  {
    "id": "kr.course.2022.high.9a1d8ebd919e690f",
    "level": "high",
    "subjectGroup": "과학 계열",
    "name": "전문 수학",
    "category": "진로 선택",
    "topics": [
      "기하",
      "삼각함수와 미적분",
      "확률과 통계"
    ]
  },
  {
    "id": "kr.course.2022.high.f2c9b5eb6dc8dab3",
    "level": "high",
    "subjectGroup": "과학 계열",
    "name": "정보과학",
    "category": "진로 선택",
    "topics": [
      "데이터 구조",
      "알고리즘",
      "정보과학 프로젝트",
      "프로그래밍"
    ]
  },
  {
    "id": "kr.course.2022.high.08e05bce52c7c12f",
    "level": "high",
    "subjectGroup": "과학 계열",
    "name": "지구과학 실험",
    "category": "융합 선택",
    "topics": [
      "고체 지구 탐구",
      "대기와 해양 탐구",
      "우주 탐구"
    ]
  },
  {
    "id": "kr.course.2022.high.55501d4acb948b2a",
    "level": "high",
    "subjectGroup": "과학 계열",
    "name": "화학 실험",
    "category": "융합 선택",
    "topics": [
      "물질의 성질",
      "탄소 화합물의 합성과 특성",
      "화학 반응",
      "화학 실험의 기초"
    ]
  },
  {
    "id": "kr.course.2022.high.995fb9fd041626a2",
    "level": "high",
    "subjectGroup": "교양",
    "name": "교육의 이해",
    "category": "진로 선택",
    "topics": [
      "교육 제도",
      "교육 활동",
      "교육의 의미와 중요성",
      "미래 교육"
    ]
  },
  {
    "id": "kr.course.2022.high.01ee08bbb919b4f4",
    "level": "high",
    "subjectGroup": "교양",
    "name": "논리와 사고",
    "category": "진로 선택",
    "topics": [
      "과학과 논리",
      "기호와 논리",
      "생활과 논리",
      "언어와 논리"
    ]
  },
  {
    "id": "kr.course.2022.high.a6cccc2ee7ccc247",
    "level": "high",
    "subjectGroup": "교양",
    "name": "논술",
    "category": "융합 선택",
    "topics": [
      "논술과 비판적 사고",
      "요약하는 글쓰기",
      "주장하는 글쓰기",
      "평가하는 글쓰기"
    ]
  },
  {
    "id": "kr.course.2022.high.14102770a0bbd5a9",
    "level": "high",
    "subjectGroup": "교양",
    "name": "보건",
    "category": "진로 선택",
    "topics": [
      "건강안전과 응급처치",
      "건강자원과 건강문화",
      "건강증진과 질병예방",
      "성과 건강",
      "정서와 정신건강"
    ]
  },
  {
    "id": "kr.course.2022.high.c82df4b549740b1b",
    "level": "high",
    "subjectGroup": "교양",
    "name": "삶과 종교",
    "category": "진로 선택",
    "topics": [
      "다양한 종교에 대한 이해",
      "변화하는 사회와 종교",
      "인간과 종교",
      "종교 문화유산"
    ]
  },
  {
    "id": "kr.course.2022.high.1a3cceb94fcda565",
    "level": "high",
    "subjectGroup": "교양",
    "name": "생태와 환경",
    "category": "일반 선택",
    "topics": [
      "기후위기와 기후행동",
      "지속가능성과 시민 참여",
      "환경 문제와 쟁점",
      "환경 체계",
      "환경과 인간"
    ]
  },
  {
    "id": "kr.course.2022.high.728909b9846a3af3",
    "level": "high",
    "subjectGroup": "교양",
    "name": "인간과 경제활동",
    "category": "융합 선택",
    "topics": [
      "인간과 경제 공동체",
      "인간과 미래 사회",
      "인간과 의사 결정",
      "인간과 직업 세계"
    ]
  },
  {
    "id": "kr.course.2022.high.e28a552fb364db7f",
    "level": "high",
    "subjectGroup": "교양",
    "name": "인간과 심리",
    "category": "진로 선택",
    "topics": [
      "마음의 과학적 탐구",
      "삶과 적응",
      "자기 이해",
      "타인 이해"
    ]
  },
  {
    "id": "kr.course.2022.high.d7b38b403d0daa71",
    "level": "high",
    "subjectGroup": "교양",
    "name": "인간과 철학",
    "category": "진로 선택",
    "topics": [
      "공동체와 철학함",
      "나의 삶과 철학함",
      "생태계와 철학함",
      "창조성과 철학함"
    ]
  },
  {
    "id": "kr.course.2022.high.bbd850cda9d2eacf",
    "level": "high",
    "subjectGroup": "교양",
    "name": "진로와 직업",
    "category": "일반 선택",
    "topics": [
      "직업 세계와 진로 탐색",
      "진로 설계와 실천",
      "진로와 나의 이해"
    ]
  },
  {
    "id": "kr.course.2022.high.4166f628015541ac",
    "level": "high",
    "subjectGroup": "국어",
    "name": "공통국어1",
    "category": "공통",
    "topics": [
      "듣기⋅말하기",
      "매체",
      "문법",
      "문학",
      "쓰기",
      "읽기"
    ]
  },
  {
    "id": "kr.course.2022.high.08a52bc2723f8254",
    "level": "high",
    "subjectGroup": "국어",
    "name": "공통국어2",
    "category": "공통",
    "topics": [
      "듣기⋅말하기",
      "매체",
      "문법",
      "문학",
      "쓰기",
      "읽기"
    ]
  },
  {
    "id": "kr.course.2022.high.ad5028dbc3343f34",
    "level": "high",
    "subjectGroup": "국어",
    "name": "독서 토론과 글쓰기",
    "category": "융합 선택",
    "topics": [
      "책을 바탕으로 삶을 탐구하고 성찰하며 자신과 공동체의 문제를 적극적으로 해결한다."
    ]
  },
  {
    "id": "kr.course.2022.high.e25a4f5a23afbd53",
    "level": "high",
    "subjectGroup": "국어",
    "name": "독서와 작문",
    "category": "일반 선택",
    "topics": [
      "평생 독자 및 평생 필자로서의 주도성과 책임감을 가지고 문어 의사소통을 실천하고, 이를"
    ]
  },
  {
    "id": "kr.course.2022.high.b06396bb85a4ce88",
    "level": "high",
    "subjectGroup": "국어",
    "name": "매체 의사소통",
    "category": "융합 선택",
    "topics": [
      "실제 삶에서 경험하는 매체 의사소통 현상에 주도적이고 협력적인 태도로 참여하여 바람직한"
    ]
  },
  {
    "id": "kr.course.2022.high.3d6576f4f53fd651",
    "level": "high",
    "subjectGroup": "국어",
    "name": "문학",
    "category": "일반 선택",
    "topics": [
      "문학을 통해 자아를 성찰하고 타자를 이해하며 공동체의 문제에 공감하고 참여하는 태도를"
    ]
  },
  {
    "id": "kr.course.2022.high.52bd240fd81d7779",
    "level": "high",
    "subjectGroup": "국어",
    "name": "문학과 영상",
    "category": "진로 선택",
    "topics": [
      "문학과 영상을 통해 자신을 성찰하고 세계와 소통하는 태도를 기르며 관련 분야의 학업과"
    ]
  },
  {
    "id": "kr.course.2022.high.ceb9dd2544d800f8",
    "level": "high",
    "subjectGroup": "국어",
    "name": "언어생활 탐구",
    "category": "융합 선택",
    "topics": [
      "언어의 힘과 가치를 이해하고 바람직한 언어문화 실천에 능동적으로 참여한다."
    ]
  },
  {
    "id": "kr.course.2022.high.eadd896d14e0e595",
    "level": "high",
    "subjectGroup": "국어",
    "name": "주제 탐구 독서",
    "category": "진로 선택",
    "topics": [
      "주제를 탐구하는 독서를 통해 학업과 진로를 적극적으로 탐색하며 자신의 삶을 성찰하고"
    ]
  },
  {
    "id": "kr.course.2022.high.2d7e009bac947d08",
    "level": "high",
    "subjectGroup": "국어",
    "name": "직무 의사소통",
    "category": "진로 선택",
    "topics": [
      "직무 환경 변화에 대응하여 지속적으로 자기를 계발하고 직무 공동체의 성장을 촉진하며"
    ]
  },
  {
    "id": "kr.course.2022.high.0c5b1f3120b2156f",
    "level": "high",
    "subjectGroup": "국어",
    "name": "화법과 언어",
    "category": "일반 선택",
    "topics": [
      "화법과 언어에 대한 성찰을 통하여 자신의 국어생활을 개선하고 바람직한 의사소통 문화"
    ]
  },
  {
    "id": "kr.course.2022.high.555fee91e0f5a8df",
    "level": "high",
    "subjectGroup": "기술·가정/정보",
    "name": "기술⋅가정",
    "category": "일반 선택",
    "topics": [
      "공학의 기초",
      "미래를 여는 공학 혁신",
      "생활문화와 디지털 환경",
      "소비자와 생활복지",
      "인간과 성장하는 관계",
      "지속가능한 융합 공학"
    ]
  },
  {
    "id": "kr.course.2022.high.edf7d80da6f9abc7",
    "level": "high",
    "subjectGroup": "기술·가정/정보",
    "name": "데이터 과학",
    "category": "진로 선택",
    "topics": [
      "데이터 과학 프로젝트",
      "데이터 과학의 이해",
      "데이터 모델링과 평가",
      "데이터 준비와 분석"
    ]
  },
  {
    "id": "kr.course.2022.high.3f8e42a8e51cf11d",
    "level": "high",
    "subjectGroup": "기술·가정/정보",
    "name": "로봇과 공학세계",
    "category": "진로 선택",
    "topics": [
      "공학세계의 탐색과 로봇의 활용",
      "로봇공학 프로젝트",
      "로봇의 이해"
    ]
  },
  {
    "id": "kr.course.2022.high.646724eed0ea6def",
    "level": "high",
    "subjectGroup": "기술·가정/정보",
    "name": "생애 설계와 자립",
    "category": "융합 선택",
    "topics": [
      "경제적 자립",
      "사회⋅정서적 자립",
      "일상생활 자립"
    ]
  },
  {
    "id": "kr.course.2022.high.64bc8da5e0581507",
    "level": "high",
    "subjectGroup": "기술·가정/정보",
    "name": "생활과학 탐구",
    "category": "진로 선택",
    "topics": [
      "생활과학과 진로",
      "생활환경과 생활과학",
      "인간행동과 생활과학"
    ]
  },
  {
    "id": "kr.course.2022.high.85930938b272eea5",
    "level": "high",
    "subjectGroup": "기술·가정/정보",
    "name": "소프트웨어와 생활",
    "category": "융합 선택",
    "topics": [
      "가치를 창출하는 소프트웨어",
      "모의 실험하는 소프트웨어",
      "세상을 변화시키는 소프트웨어",
      "창작을 지원하는 소프트웨어",
      "현상을 분석하는 소프트웨어"
    ]
  },
  {
    "id": "kr.course.2022.high.ec9979c5e9dcdbba",
    "level": "high",
    "subjectGroup": "기술·가정/정보",
    "name": "아동발달과 부모",
    "category": "융합 선택",
    "topics": [
      "부모됨의 준비",
      "아동발달과 돌봄"
    ]
  },
  {
    "id": "kr.course.2022.high.145152075acdd93e",
    "level": "high",
    "subjectGroup": "기술·가정/정보",
    "name": "인공지능 기초",
    "category": "진로 선택",
    "topics": [
      "인공지능 프로젝트",
      "인공지능과 학습",
      "인공지능의 사회적 영향",
      "인공지능의 이해"
    ]
  },
  {
    "id": "kr.course.2022.high.d37b249570ba229d",
    "level": "high",
    "subjectGroup": "기술·가정/정보",
    "name": "정보",
    "category": "일반 선택",
    "topics": [
      "데이터",
      "디지털 문화",
      "알고리즘과 프로그래밍",
      "인공지능",
      "컴퓨팅 시스템"
    ]
  },
  {
    "id": "kr.course.2022.high.231db579e1a3b213",
    "level": "high",
    "subjectGroup": "기술·가정/정보",
    "name": "지식 재산 일반",
    "category": "융합 선택",
    "topics": [
      "지식재산권 창출 프로젝트",
      "지식재산권의 보호와 활용",
      "지식재산의 이해"
    ]
  },
  {
    "id": "kr.course.2022.high.74610e8ebab5b4a1",
    "level": "high",
    "subjectGroup": "기술·가정/정보",
    "name": "창의 공학 설계",
    "category": "융합 선택",
    "topics": [
      "창의 공학 설계 프로젝트",
      "창의 공학 설계의 이해"
    ]
  },
  {
    "id": "kr.course.2022.high.f86f4fdd4d8bd850",
    "level": "high",
    "subjectGroup": "도덕",
    "name": "윤리문제 탐구",
    "category": "융합 선택",
    "topics": [
      "생태적 삶과 윤리적 탐구",
      "시민의 삶과 윤리적 탐구",
      "윤리문제 탐구의 이해",
      "윤리문제 탐구의 적용",
      "인공지능 시대의 삶과 윤리적 탐구"
    ]
  },
  {
    "id": "kr.course.2022.high.a1b18270d3952c04",
    "level": "high",
    "subjectGroup": "도덕",
    "name": "윤리와 사상",
    "category": "진로 선택",
    "topics": [
      "동양 윤리사상",
      "사회사상",
      "서양 윤리사상",
      "한국 윤리사상"
    ]
  },
  {
    "id": "kr.course.2022.high.1f3546a829ffdecb",
    "level": "high",
    "subjectGroup": "도덕",
    "name": "인문학과 윤리",
    "category": "진로 선택",
    "topics": [
      "공존과 지속가능성",
      "다양성과 포용성",
      "삶의 의미에 대한 물음",
      "성찰 대상으로서 나",
      "자유와 평등",
      "타인과 관계 맺기"
    ]
  },
  {
    "id": "kr.course.2022.high.c89123c129b62d34",
    "level": "high",
    "subjectGroup": "도덕",
    "name": "현대사회와 윤리",
    "category": "일반 선택",
    "topics": [
      "과학과 디지털 학습 환경 윤리",
      "문화와 경제생활의 윤리",
      "민주시민과 윤리",
      "생명윤리와 생태윤리",
      "평화와 공존의 윤리",
      "현대 생활과 윤리"
    ]
  },
  {
    "id": "kr.course.2022.high.820636c315f9a521",
    "level": "high",
    "subjectGroup": "미술",
    "name": "미술",
    "category": "일반 선택",
    "topics": [
      "감상",
      "미적 체험",
      "표현"
    ]
  },
  {
    "id": "kr.course.2022.high.bd6954f123f77b19",
    "level": "high",
    "subjectGroup": "미술",
    "name": "미술 감상과 비평",
    "category": "진로 선택",
    "topics": [
      "미술 감상",
      "미술 비평"
    ]
  },
  {
    "id": "kr.course.2022.high.684550635ae22e69",
    "level": "high",
    "subjectGroup": "미술",
    "name": "미술 창작",
    "category": "진로 선택",
    "topics": [
      "설계와 창작",
      "창작의 확장"
    ]
  },
  {
    "id": "kr.course.2022.high.f813f71ccff347a5",
    "level": "high",
    "subjectGroup": "미술",
    "name": "미술과 매체",
    "category": "융합 선택",
    "topics": [
      "매체의 이해",
      "매체의 활용"
    ]
  },
  {
    "id": "kr.course.2022.high.73b8f67500b2f635",
    "level": "high",
    "subjectGroup": "사회(역사 포함)",
    "name": "경제",
    "category": "진로 선택",
    "topics": [
      "거시 경제",
      "경제학과 경제 문제",
      "국제 경제",
      "미시 경제"
    ]
  },
  {
    "id": "kr.course.2022.high.b99da18bd4261282",
    "level": "high",
    "subjectGroup": "사회(역사 포함)",
    "name": "국제 관계의 이해",
    "category": "진로 선택",
    "topics": [
      "국제 관계의 특징",
      "국제 분쟁의 해결",
      "균형 발전과 상생",
      "평화와 안전의 보장"
    ]
  },
  {
    "id": "kr.course.2022.high.9c68b4a5acf7bc54",
    "level": "high",
    "subjectGroup": "사회(역사 포함)",
    "name": "금융과 경제생활",
    "category": "융합 선택",
    "topics": [
      "수입과 지출",
      "신용과 위험 관리",
      "저축과 투자",
      "행복하고 안전한 금융 생활"
    ]
  },
  {
    "id": "kr.course.2022.high.d44038d624b2c0e8",
    "level": "high",
    "subjectGroup": "사회(역사 포함)",
    "name": "기후변화와 지속가능한 세계",
    "category": "융합 선택",
    "topics": [
      "공존의 세계와 생태시민",
      "기후정의와 지역문제",
      "인간과 기후변화",
      "지속가능한 세계를 위한 생태전환"
    ]
  },
  {
    "id": "kr.course.2022.high.939b117c5645223c",
    "level": "high",
    "subjectGroup": "사회(역사 포함)",
    "name": "도시의 미래 탐구",
    "category": "진로 선택",
    "topics": [
      "도시 문제와 공간 정의",
      "도시의 미래",
      "변화하는 도시",
      "삶의 공간, 도시"
    ]
  },
  {
    "id": "kr.course.2022.high.dafb350c0a175866",
    "level": "high",
    "subjectGroup": "사회(역사 포함)",
    "name": "동아시아 역사 기행",
    "category": "진로 선택",
    "topics": [
      "교류와 갈등의 현장에서 만난 역사",
      "동아시아로 떠나는 역사 기행",
      "침략과 저항의 현장에서 만난 역사",
      "평화와 공존의 현장에서 만난 역사"
    ]
  },
  {
    "id": "kr.course.2022.high.6d1ef8fa11ebf6cc",
    "level": "high",
    "subjectGroup": "사회(역사 포함)",
    "name": "법과 사회",
    "category": "진로 선택",
    "topics": [
      "개인 생활과 법",
      "국가 생활과 법",
      "사회생활과 법",
      "학교생활과 법"
    ]
  },
  {
    "id": "kr.course.2022.high.0a5ca60cb2cc7cb3",
    "level": "high",
    "subjectGroup": "사회(역사 포함)",
    "name": "사회문제 탐구",
    "category": "융합 선택",
    "topics": [
      "변화하는 세계와 사회문제",
      "사회문제 사례 연구",
      "사회문제의 이해와 탐구",
      "일상생활과 사회문제"
    ]
  },
  {
    "id": "kr.course.2022.high.e1095c22fa239a45",
    "level": "high",
    "subjectGroup": "사회(역사 포함)",
    "name": "사회와 문화",
    "category": "일반 선택",
    "topics": [
      "사회 구조와 사회 변동",
      "사회 불평등과 사회 복지",
      "사회현상의 이해와 탐구",
      "일상 문화와 문화 변동"
    ]
  },
  {
    "id": "kr.course.2022.high.40a37cbb066524dc",
    "level": "high",
    "subjectGroup": "사회(역사 포함)",
    "name": "세계사",
    "category": "일반 선택",
    "topics": [
      "교역망의 확대",
      "국민 국가의 형성",
      "지역 세계의 형성",
      "현대 세계의 과제"
    ]
  },
  {
    "id": "kr.course.2022.high.8d92b38799a93bd4",
    "level": "high",
    "subjectGroup": "사회(역사 포함)",
    "name": "세계시민과 지리",
    "category": "일반 선택",
    "topics": [
      "네트워크 세계, 세계의 인구와 경제 공간",
      "모자이크 세계, 세계의 다양한 자연환경과 문화",
      "세계시민, 세계화와 지역 이해",
      "지속가능한 세계, 세계의 환경 문제와 평화"
    ]
  },
  {
    "id": "kr.course.2022.high.b21f5ae348e51acf",
    "level": "high",
    "subjectGroup": "사회(역사 포함)",
    "name": "여행지리",
    "category": "융합 선택",
    "topics": [
      "문화와 자연을 찾아가는 여행",
      "미래 사회와 여행",
      "성찰과 공존을 위한 여행",
      "행복하고 안전한 여행"
    ]
  },
  {
    "id": "kr.course.2022.high.027b13711abccc78",
    "level": "high",
    "subjectGroup": "사회(역사 포함)",
    "name": "역사로 탐구하는 현대 세계",
    "category": "융합 선택",
    "topics": [
      "냉전과 열전",
      "도전받는 현대 세계",
      "분쟁과 갈등, 화해의 역사",
      "성장의 풍요와 생태환경",
      "현대 세계와 역사 탐구"
    ]
  },
  {
    "id": "kr.course.2022.high.f077a73079be6827",
    "level": "high",
    "subjectGroup": "사회(역사 포함)",
    "name": "정치",
    "category": "진로 선택",
    "topics": [
      "국제 사회와 정치",
      "민주 국가의 정부 형태",
      "시민 생활과 정치",
      "정치과정과 참여"
    ]
  },
  {
    "id": "kr.course.2022.high.39d5366ad464cca2",
    "level": "high",
    "subjectGroup": "사회(역사 포함)",
    "name": "통합사회1",
    "category": "공통",
    "topics": [
      "문화와 다양성",
      "생활공간과 사회",
      "인간, 사회, 환경과 행복",
      "자연환경과 인간",
      "통합적 관점"
    ]
  },
  {
    "id": "kr.course.2022.high.80056ae9aae18563",
    "level": "high",
    "subjectGroup": "사회(역사 포함)",
    "name": "통합사회2",
    "category": "공통",
    "topics": [
      "미래와 지속가능한 삶",
      "사회정의와 불평등",
      "세계화와 평화",
      "시장경제와 지속가능발전",
      "인권보장과 헌법"
    ]
  },
  {
    "id": "kr.course.2022.high.8d43b2271a6b33db",
    "level": "high",
    "subjectGroup": "사회(역사 포함)",
    "name": "한국사1",
    "category": "공통",
    "topics": [
      "근대 국가 수립의 노력",
      "근대 이전 한국사의 이해",
      "근대 이전 한국사의 탐구"
    ]
  },
  {
    "id": "kr.course.2022.high.310c440f00072a3a",
    "level": "high",
    "subjectGroup": "사회(역사 포함)",
    "name": "한국사2",
    "category": "공통",
    "topics": [
      "대한민국의 발전",
      "오늘날의 대한민국",
      "일제 식민 통치와 민족운동"
    ]
  },
  {
    "id": "kr.course.2022.high.b70eb35a8c813c87",
    "level": "high",
    "subjectGroup": "사회(역사 포함)",
    "name": "한국지리 탐구",
    "category": "진로 선택",
    "topics": [
      "공간정보와 지리 탐구",
      "국토의 변화와 균형 발전 탐구",
      "동아시아 갈등과 공존 탐구",
      "생활 속 지리 탐구",
      "환경과 지속가능성 탐구"
    ]
  },
  {
    "id": "kr.course.2022.high.ea6554729c3abd96",
    "level": "high",
    "subjectGroup": "수학",
    "name": "경제 수학",
    "category": "진로 선택",
    "topics": [
      "미분과 경제",
      "수와 경제",
      "함수와 경제",
      "행렬과 경제"
    ]
  },
  {
    "id": "kr.course.2022.high.c5134bb916edf899",
    "level": "high",
    "subjectGroup": "수학",
    "name": "공통수학1",
    "category": "공통",
    "topics": [
      "경우의 수",
      "다항식",
      "방정식과 부등식",
      "행렬"
    ]
  },
  {
    "id": "kr.course.2022.high.f699e06d5f857844",
    "level": "high",
    "subjectGroup": "수학",
    "name": "공통수학2",
    "category": "공통",
    "topics": [
      "도형의 방정식",
      "집합과 명제",
      "함수와 그래프"
    ]
  },
  {
    "id": "kr.course.2022.high.f0d7204a23c5c159",
    "level": "high",
    "subjectGroup": "수학",
    "name": "기본수학1",
    "category": "공통",
    "topics": [
      "경우의 수",
      "다항식",
      "방정식과 부등식",
      "행렬"
    ]
  },
  {
    "id": "kr.course.2022.high.8fda79d3e68f95aa",
    "level": "high",
    "subjectGroup": "수학",
    "name": "기본수학2",
    "category": "공통",
    "topics": [
      "도형의 방정식",
      "집합과 명제",
      "함수와 그래프"
    ]
  },
  {
    "id": "kr.course.2022.high.618d9440455dea57",
    "level": "high",
    "subjectGroup": "수학",
    "name": "기하",
    "category": "진로 선택",
    "topics": [
      "공간도형과 공간좌표",
      "벡터",
      "이차곡선"
    ]
  },
  {
    "id": "kr.course.2022.high.c792f480cf5de7d8",
    "level": "high",
    "subjectGroup": "수학",
    "name": "대수",
    "category": "일반 선택",
    "topics": [
      "삼각함수",
      "수열",
      "지수함수와 로그함수"
    ]
  },
  {
    "id": "kr.course.2022.high.40c49396f0b4120a",
    "level": "high",
    "subjectGroup": "수학",
    "name": "미적분Ⅰ",
    "category": "일반 선택",
    "topics": [
      "미분",
      "적분",
      "함수의 극한과 연속"
    ]
  },
  {
    "id": "kr.course.2022.high.f2f37c909b8de62e",
    "level": "high",
    "subjectGroup": "수학",
    "name": "미적분Ⅱ",
    "category": "진로 선택",
    "topics": [
      "미분법",
      "수열의 극한",
      "적분법"
    ]
  },
  {
    "id": "kr.course.2022.high.d81ba5ecef1483f1",
    "level": "high",
    "subjectGroup": "수학",
    "name": "수학과 문화",
    "category": "융합 선택",
    "topics": [
      "사회와 수학",
      "생활과 수학",
      "예술과 수학",
      "환경과 수학"
    ]
  },
  {
    "id": "kr.course.2022.high.bf0306b33da218c2",
    "level": "high",
    "subjectGroup": "수학",
    "name": "수학과제 탐구",
    "category": "융합 선택",
    "topics": [
      "과제 탐구의 방법과 절차",
      "과제 탐구의 실행 및 평가",
      "과제 탐구의 이해"
    ]
  },
  {
    "id": "kr.course.2022.high.10206858fed637ba",
    "level": "high",
    "subjectGroup": "수학",
    "name": "실용 통계",
    "category": "융합 선택",
    "topics": [
      "자료의 분석",
      "자료의 수집과 정리",
      "통계와 통계적 문제",
      "통계적 탐구"
    ]
  },
  {
    "id": "kr.course.2022.high.626208622123727d",
    "level": "high",
    "subjectGroup": "수학",
    "name": "인공지능 수학",
    "category": "진로 선택",
    "topics": [
      "예측과 최적화",
      "이미지 데이터 처리",
      "인공지능과 빅데이터",
      "인공지능과 수학 탐구",
      "텍스트 데이터 처리"
    ]
  },
  {
    "id": "kr.course.2022.high.3c5f96a75054f7d6",
    "level": "high",
    "subjectGroup": "수학",
    "name": "직무 수학",
    "category": "진로 선택",
    "topics": [
      "도형과 측정",
      "변화와 관계",
      "수와 연산",
      "자료와 가능성"
    ]
  },
  {
    "id": "kr.course.2022.high.4614f96eca3261d1",
    "level": "high",
    "subjectGroup": "수학",
    "name": "확률과 통계",
    "category": "일반 선택",
    "topics": [
      "경우의 수",
      "통계",
      "확률"
    ]
  },
  {
    "id": "kr.course.2022.high.1aa7a52049208785",
    "level": "high",
    "subjectGroup": "영어",
    "name": "공통영어1",
    "category": "공통",
    "topics": [
      "이해",
      "표현"
    ]
  },
  {
    "id": "kr.course.2022.high.b500bfc2d692a67a",
    "level": "high",
    "subjectGroup": "영어",
    "name": "공통영어2",
    "category": "공통",
    "topics": [
      "이해",
      "표현"
    ]
  },
  {
    "id": "kr.course.2022.high.1a2a0f41692de8e3",
    "level": "high",
    "subjectGroup": "영어",
    "name": "기본영어1",
    "category": "공통",
    "topics": [
      "이해",
      "표현"
    ]
  },
  {
    "id": "kr.course.2022.high.04c2bef80f49173a",
    "level": "high",
    "subjectGroup": "영어",
    "name": "기본영어2",
    "category": "공통",
    "topics": [
      "이해",
      "표현"
    ]
  },
  {
    "id": "kr.course.2022.high.13e453c37845e746",
    "level": "high",
    "subjectGroup": "영어",
    "name": "미디어 영어",
    "category": "융합 선택",
    "topics": [
      "영역 01"
    ]
  },
  {
    "id": "kr.course.2022.high.306b8ae8b21876da",
    "level": "high",
    "subjectGroup": "영어",
    "name": "세계 문화와 영어",
    "category": "융합 선택",
    "topics": [
      "영역 01"
    ]
  },
  {
    "id": "kr.course.2022.high.ac8aa2b7149e9d5d",
    "level": "high",
    "subjectGroup": "영어",
    "name": "실생활 영어 회화",
    "category": "융합 선택",
    "topics": [
      "영역 01"
    ]
  },
  {
    "id": "kr.course.2022.high.101e5211e2e07253",
    "level": "high",
    "subjectGroup": "영어",
    "name": "심화 영어",
    "category": "진로 선택",
    "topics": [
      "이해",
      "표현"
    ]
  },
  {
    "id": "kr.course.2022.high.b1d0acec220f3051",
    "level": "high",
    "subjectGroup": "영어",
    "name": "심화 영어 독해와 작문",
    "category": "진로 선택",
    "topics": [
      "독해",
      "작문"
    ]
  },
  {
    "id": "kr.course.2022.high.bec9f759cd83885f",
    "level": "high",
    "subjectGroup": "영어",
    "name": "영미 문학 읽기",
    "category": "진로 선택",
    "topics": [
      "영역 01"
    ]
  },
  {
    "id": "kr.course.2022.high.fc40e63c46a838a9",
    "level": "high",
    "subjectGroup": "영어",
    "name": "영어 독해와 작문",
    "category": "일반 선택",
    "topics": [
      "독해",
      "작문"
    ]
  },
  {
    "id": "kr.course.2022.high.58c5c33e945d5350",
    "level": "high",
    "subjectGroup": "영어",
    "name": "영어 발표와 토론",
    "category": "진로 선택",
    "topics": [
      "발표",
      "토론"
    ]
  },
  {
    "id": "kr.course.2022.high.5303ffa8a293a42a",
    "level": "high",
    "subjectGroup": "영어",
    "name": "영어 I",
    "category": "일반 선택",
    "topics": [
      "이해",
      "표현"
    ]
  },
  {
    "id": "kr.course.2022.high.586e769f7ff7d976",
    "level": "high",
    "subjectGroup": "영어",
    "name": "영어 Ⅱ",
    "category": "일반 선택",
    "topics": [
      "이해",
      "표현"
    ]
  },
  {
    "id": "kr.course.2022.high.ac8d5ed8f99fc56c",
    "level": "high",
    "subjectGroup": "영어",
    "name": "직무 영어",
    "category": "진로 선택",
    "topics": [
      "영역 01"
    ]
  },
  {
    "id": "kr.course.2022.high.c10608cd75732d16",
    "level": "high",
    "subjectGroup": "예술 계열",
    "name": "극 창작",
    "category": "진로 선택",
    "topics": [
      "극 창작의 실제",
      "극 창작의 원리"
    ]
  },
  {
    "id": "kr.course.2022.high.f916f7d9ccc2a6b8",
    "level": "high",
    "subjectGroup": "예술 계열",
    "name": "드로잉",
    "category": "진로 선택",
    "topics": [
      "이해",
      "재료와 기법",
      "표현"
    ]
  },
  {
    "id": "kr.course.2022.high.f2938bc832866164",
    "level": "high",
    "subjectGroup": "예술 계열",
    "name": "무대미술과 기술",
    "category": "진로 선택",
    "topics": [
      "무대분장",
      "무대음향",
      "무대의상",
      "무대장치",
      "무대조명"
    ]
  },
  {
    "id": "kr.course.2022.high.6a2318c299940152",
    "level": "high",
    "subjectGroup": "예술 계열",
    "name": "무용 감상과 비평",
    "category": "진로 선택",
    "topics": [
      "무용 감상과 비평의 실제",
      "무용 감상과 비평의 이해"
    ]
  },
  {
    "id": "kr.course.2022.high.803a13272c403893",
    "level": "high",
    "subjectGroup": "예술 계열",
    "name": "무용 기초 실기",
    "category": "진로 선택",
    "topics": [
      "기본 동작 심화",
      "기본 동작 원리"
    ]
  },
  {
    "id": "kr.course.2022.high.1c7ac7f420ed071b",
    "level": "high",
    "subjectGroup": "예술 계열",
    "name": "무용 전공 실기",
    "category": "진로 선택",
    "topics": [
      "응용 동작",
      "작품 실기"
    ]
  },
  {
    "id": "kr.course.2022.high.2a58000c9f011139",
    "level": "high",
    "subjectGroup": "예술 계열",
    "name": "무용 제작 실습",
    "category": "진로 선택",
    "topics": [
      "무용 제작의 실제",
      "무용 제작의 이해"
    ]
  },
  {
    "id": "kr.course.2022.high.431ec6ab789af437",
    "level": "high",
    "subjectGroup": "예술 계열",
    "name": "무용과 매체",
    "category": "진로 선택",
    "topics": [
      "무용에서 매체의 이해",
      "무용에서 매체의 활용"
    ]
  },
  {
    "id": "kr.course.2022.high.69c14b5ce38f4fd3",
    "level": "high",
    "subjectGroup": "예술 계열",
    "name": "무용과 몸",
    "category": "진로 선택",
    "topics": [
      "몸의 이해와 성찰",
      "춤추는 몸"
    ]
  },
  {
    "id": "kr.course.2022.high.bfa0037a3abdebad",
    "level": "high",
    "subjectGroup": "예술 계열",
    "name": "무용의 이해",
    "category": "진로 선택",
    "topics": [
      "무용과 삶",
      "무용의 역사"
    ]
  },
  {
    "id": "kr.course.2022.high.f19ca43977fa2e0c",
    "level": "high",
    "subjectGroup": "예술 계열",
    "name": "문예 창작의 이해",
    "category": "진로 선택",
    "topics": [
      "문예 창작의 실제",
      "문예 창작의 원리"
    ]
  },
  {
    "id": "kr.course.2022.high.db513cec2e459809",
    "level": "high",
    "subjectGroup": "예술 계열",
    "name": "문장론",
    "category": "진로 선택",
    "topics": [
      "글 작성 과정",
      "문장 표현 방법"
    ]
  },
  {
    "id": "kr.course.2022.high.ee57fe51c50463ee",
    "level": "high",
    "subjectGroup": "예술 계열",
    "name": "문학 감상과 비평",
    "category": "진로 선택",
    "topics": [
      "문학 감상과 비평의 실제",
      "문학 감상과 비평의 원리"
    ]
  },
  {
    "id": "kr.course.2022.high.6198a0b96b7cda38",
    "level": "high",
    "subjectGroup": "예술 계열",
    "name": "문학과 매체",
    "category": "융합 선택",
    "topics": [
      "다매체 시대의 문학",
      "문학의 확장과 융합"
    ]
  },
  {
    "id": "kr.course.2022.high.44d7fe59965cd66d",
    "level": "high",
    "subjectGroup": "예술 계열",
    "name": "미술 매체 탐구",
    "category": "진로 선택",
    "topics": [
      "이해",
      "표현",
      "확장"
    ]
  },
  {
    "id": "kr.course.2022.high.cb94aff57ea34e2c",
    "level": "high",
    "subjectGroup": "예술 계열",
    "name": "미술 이론",
    "category": "진로 선택",
    "topics": [
      "미술의 이해",
      "비평론",
      "조형론"
    ]
  },
  {
    "id": "kr.course.2022.high.06d98befd6e4d245",
    "level": "high",
    "subjectGroup": "예술 계열",
    "name": "미술 전공 실기",
    "category": "진로 선택",
    "topics": [
      "재료와 기법",
      "진로",
      "창작"
    ]
  },
  {
    "id": "kr.course.2022.high.47e5a3cf986bac11",
    "level": "high",
    "subjectGroup": "예술 계열",
    "name": "미술과 사회",
    "category": "융합 선택",
    "topics": [
      "미술과 소통",
      "미술과 참여",
      "미술의 확장"
    ]
  },
  {
    "id": "kr.course.2022.high.dfbfa0a4e48ef273",
    "level": "high",
    "subjectGroup": "예술 계열",
    "name": "미술사",
    "category": "진로 선택",
    "topics": [
      "미술사의 이해",
      "미술사의 확장",
      "시대·지역별 미술사"
    ]
  },
  {
    "id": "kr.course.2022.high.ef07bfea6b4d6456",
    "level": "high",
    "subjectGroup": "예술 계열",
    "name": "사진 감상과 비평",
    "category": "진로 선택",
    "topics": [
      "작품 감상과 비평",
      "창의적 사고의 확장"
    ]
  },
  {
    "id": "kr.course.2022.high.19c478454e6368bf",
    "level": "high",
    "subjectGroup": "예술 계열",
    "name": "사진 촬영",
    "category": "진로 선택",
    "topics": [
      "사진 제작",
      "사진 촬영과 조명"
    ]
  },
  {
    "id": "kr.course.2022.high.a797f76ec42a23ac",
    "level": "high",
    "subjectGroup": "예술 계열",
    "name": "사진 표현 기법",
    "category": "진로 선택",
    "topics": [
      "이미지 표현",
      "이미지 활용"
    ]
  },
  {
    "id": "kr.course.2022.high.363f791733fdf870",
    "level": "high",
    "subjectGroup": "예술 계열",
    "name": "사진과 삶",
    "category": "진로 선택",
    "topics": [
      "사진과 일상",
      "생각과 표현"
    ]
  },
  {
    "id": "kr.course.2022.high.13860b6d47df9168",
    "level": "high",
    "subjectGroup": "예술 계열",
    "name": "사진의 이해",
    "category": "진로 선택",
    "topics": [
      "사진의 개념",
      "사진의 표현"
    ]
  },
  {
    "id": "kr.course.2022.high.6159ad4851e8486a",
    "level": "high",
    "subjectGroup": "예술 계열",
    "name": "소설 창작",
    "category": "진로 선택",
    "topics": [
      "소설 창작의 실제",
      "소설 창작의 원리"
    ]
  },
  {
    "id": "kr.course.2022.high.daffc87de6f60cd1",
    "level": "high",
    "subjectGroup": "예술 계열",
    "name": "시 창작",
    "category": "진로 선택",
    "topics": [
      "시 창작의 실제",
      "시 창작의 원리"
    ]
  },
  {
    "id": "kr.course.2022.high.e5bfe10adbf0f80b",
    "level": "high",
    "subjectGroup": "예술 계열",
    "name": "시창 · 청음",
    "category": "진로 선택",
    "topics": [
      "음악적 탐구",
      "음악적 표현"
    ]
  },
  {
    "id": "kr.course.2022.high.6c1ec3797d54a8ce",
    "level": "high",
    "subjectGroup": "예술 계열",
    "name": "안무",
    "category": "진로 선택",
    "topics": [
      "안무 원리와 방법",
      "안무의 과정"
    ]
  },
  {
    "id": "kr.course.2022.high.4fe4c9a1f2969e05",
    "level": "high",
    "subjectGroup": "예술 계열",
    "name": "연극",
    "category": "진로 선택",
    "topics": [
      "감상",
      "생활",
      "체험",
      "표현"
    ]
  },
  {
    "id": "kr.course.2022.high.58202516d750232c",
    "level": "high",
    "subjectGroup": "예술 계열",
    "name": "연극 감상과 비평",
    "category": "진로 선택",
    "topics": [
      "감상과 비평의 실제",
      "감상과 비평의 이해"
    ]
  },
  {
    "id": "kr.course.2022.high.672b18be789004e4",
    "level": "high",
    "subjectGroup": "예술 계열",
    "name": "연극 제작 실습",
    "category": "진로 선택",
    "topics": [
      "공연",
      "제작",
      "준비"
    ]
  },
  {
    "id": "kr.course.2022.high.0474b7d133a7462b",
    "level": "high",
    "subjectGroup": "예술 계열",
    "name": "연극과 말",
    "category": "진로 선택",
    "topics": [
      "이해",
      "표현",
      "훈련"
    ]
  },
  {
    "id": "kr.course.2022.high.91c0dc0a99e842fc",
    "level": "high",
    "subjectGroup": "예술 계열",
    "name": "연극과 몸",
    "category": "일반 선택",
    "topics": [
      "이해",
      "표현",
      "훈련"
    ]
  },
  {
    "id": "kr.course.2022.high.7c8b0de4c3e7a026",
    "level": "high",
    "subjectGroup": "예술 계열",
    "name": "연극과 삶",
    "category": "진로 선택",
    "topics": [
      "연극과 직업",
      "연극의 특성",
      "연극의 흐름",
      "일상과 연극"
    ]
  },
  {
    "id": "kr.course.2022.high.adc41c9a88db5ca3",
    "level": "high",
    "subjectGroup": "예술 계열",
    "name": "연기",
    "category": "진로 선택",
    "topics": [
      "분석",
      "적용",
      "훈련"
    ]
  },
  {
    "id": "kr.course.2022.high.e6ab0340bd26b474",
    "level": "high",
    "subjectGroup": "예술 계열",
    "name": "영상 제작의 이해",
    "category": "진로 선택",
    "topics": [
      "영상 촬영과 편집",
      "영상 표현"
    ]
  },
  {
    "id": "kr.course.2022.high.2b0c89676b78fc66",
    "level": "high",
    "subjectGroup": "예술 계열",
    "name": "영화 감상과 비평",
    "category": "진로 선택",
    "topics": [
      "감상과 비평의 실제",
      "감상과 비평의 이해"
    ]
  },
  {
    "id": "kr.course.2022.high.4688035445209a00",
    "level": "high",
    "subjectGroup": "예술 계열",
    "name": "영화 제작 실습",
    "category": "진로 선택",
    "topics": [
      "사전 제작 단계",
      "제작 단계",
      "후반 제작 단계"
    ]
  },
  {
    "id": "kr.course.2022.high.7fcbeea9762a6602",
    "level": "high",
    "subjectGroup": "예술 계열",
    "name": "영화와 삶",
    "category": "진로 선택",
    "topics": [
      "영화로 세상읽기",
      "영화로 탐색하기",
      "영화로 표현하기"
    ]
  },
  {
    "id": "kr.course.2022.high.5b16f6819ed99927",
    "level": "high",
    "subjectGroup": "예술 계열",
    "name": "영화의 이해",
    "category": "진로 선택",
    "topics": [
      "영화의 구성 요소",
      "영화의 역사",
      "영화의 특성"
    ]
  },
  {
    "id": "kr.course.2022.high.6be6af59a250a897",
    "level": "high",
    "subjectGroup": "예술 계열",
    "name": "음악 공연 실습",
    "category": "진로 선택",
    "topics": [
      "연계적 표현",
      "음악적 탐구"
    ]
  },
  {
    "id": "kr.course.2022.high.0b54107247a15a25",
    "level": "high",
    "subjectGroup": "예술 계열",
    "name": "음악 이론",
    "category": "진로 선택",
    "topics": [
      "음악적 적용",
      "음악적 탐구"
    ]
  },
  {
    "id": "kr.course.2022.high.7928d3d6cf673fb2",
    "level": "high",
    "subjectGroup": "예술 계열",
    "name": "음악 전공 실기",
    "category": "진로 선택",
    "topics": [
      "심화적 표현",
      "음악적 탐구"
    ]
  },
  {
    "id": "kr.course.2022.high.43b3ab41469282b2",
    "level": "high",
    "subjectGroup": "예술 계열",
    "name": "음악과 문화",
    "category": "융합 선택",
    "topics": [
      "문화적 소통",
      "문화적 탐구"
    ]
  },
  {
    "id": "kr.course.2022.high.f38c74f99a9659eb",
    "level": "high",
    "subjectGroup": "예술 계열",
    "name": "음악사",
    "category": "진로 선택",
    "topics": [
      "음악적 의미",
      "음악적 탐구"
    ]
  },
  {
    "id": "kr.course.2022.high.09b9d3ec2c694b5f",
    "level": "high",
    "subjectGroup": "예술 계열",
    "name": "조형 탐구",
    "category": "진로 선택",
    "topics": [
      "조형의 기초",
      "조형의 확장"
    ]
  },
  {
    "id": "kr.course.2022.high.a3f9d8c2fb04e255",
    "level": "high",
    "subjectGroup": "예술 계열",
    "name": "촬영·조명",
    "category": "진로 선택",
    "topics": [
      "조명",
      "촬영"
    ]
  },
  {
    "id": "kr.course.2022.high.9ad3660db2e523d9",
    "level": "high",
    "subjectGroup": "예술 계열",
    "name": "편집·사운드",
    "category": "진로 선택",
    "topics": [
      "사운드",
      "편집"
    ]
  },
  {
    "id": "kr.course.2022.high.8db959b294a67e0b",
    "level": "high",
    "subjectGroup": "예술 계열",
    "name": "합창 · 합주",
    "category": "진로 선택",
    "topics": [
      "실천적 표현",
      "음악적 탐구"
    ]
  },
  {
    "id": "kr.course.2022.high.fdd5dc79d2d5fcf8",
    "level": "high",
    "subjectGroup": "음악",
    "name": "음악",
    "category": "일반 선택",
    "topics": [
      "감상",
      "연주",
      "창작"
    ]
  },
  {
    "id": "kr.course.2022.high.f0f8b02bec6bd23c",
    "level": "high",
    "subjectGroup": "음악",
    "name": "음악 감상과 비평",
    "category": "진로 선택",
    "topics": [
      "감상과 반응",
      "비평과 활용"
    ]
  },
  {
    "id": "kr.course.2022.high.b6553c21d8f53096",
    "level": "high",
    "subjectGroup": "음악",
    "name": "음악 연주와 창작",
    "category": "진로 선택",
    "topics": [
      "실천과 소통",
      "표현과 창작"
    ]
  },
  {
    "id": "kr.course.2022.high.e91386df42bd5410",
    "level": "high",
    "subjectGroup": "음악",
    "name": "음악과 미디어",
    "category": "융합 선택",
    "topics": [
      "미디어 탐구",
      "실용적 연계"
    ]
  },
  {
    "id": "kr.course.2022.high.24379bf8c674afe5",
    "level": "high",
    "subjectGroup": "제2외국어",
    "name": "독일어",
    "category": "공통",
    "topics": [
      "듣기",
      "말하기",
      "문화",
      "쓰기",
      "읽기"
    ]
  },
  {
    "id": "kr.course.2022.high.b575b524e4e20bb5",
    "level": "high",
    "subjectGroup": "제2외국어",
    "name": "독일어 회화",
    "category": "진로 선택",
    "topics": [
      "상대방의 말을 경청하며 적극적인 자세로 의사소통 활동에 참여한다."
    ]
  },
  {
    "id": "kr.course.2022.high.1c417ce887645eb9",
    "level": "high",
    "subjectGroup": "제2외국어",
    "name": "독일어권 문화",
    "category": "융합 선택",
    "topics": [
      "독일어권 문화에서 관심 있는 분야의 정보를 다양한 매체를 통해 조사하고 자신의 삶과",
      "영역 01"
    ]
  },
  {
    "id": "kr.course.2022.high.562fe30524d2e5d4",
    "level": "high",
    "subjectGroup": "제2외국어",
    "name": "러시아 문화",
    "category": "공통",
    "topics": [
      "러시아 문화를 직간접적으로 체험하고, 상호문화적 관점에서 이를 이해한다.",
      "영역 01"
    ]
  },
  {
    "id": "kr.course.2022.high.d07982c3b4598582",
    "level": "high",
    "subjectGroup": "제2외국어",
    "name": "러시아어",
    "category": "공통",
    "topics": [
      "듣기",
      "말하기",
      "문화",
      "쓰기",
      "읽기"
    ]
  },
  {
    "id": "kr.course.2022.high.d1488c35377c23d3",
    "level": "high",
    "subjectGroup": "제2외국어",
    "name": "러시아어 회화",
    "category": "일반 선택",
    "topics": [
      "일상생활에서 자주 접하는 주제에 대해 자신의 의견을 말하거나 정보를 교환한다."
    ]
  },
  {
    "id": "kr.course.2022.high.a33e1e8e7f73b6d1",
    "level": "high",
    "subjectGroup": "제2외국어",
    "name": "베트남 문화",
    "category": "융합 선택",
    "topics": [
      "다양한 매체를 활용하여 베트남 문화 중 관심 분야의 정보를 조사하고 이를 진로와 관련"
    ]
  },
  {
    "id": "kr.course.2022.high.3eb905a789303d57",
    "level": "high",
    "subjectGroup": "제2외국어",
    "name": "베트남어",
    "category": "공통",
    "topics": [
      "듣기",
      "말하기",
      "문화",
      "쓰기",
      "읽기"
    ]
  },
  {
    "id": "kr.course.2022.high.7764f2f6f62223a5",
    "level": "high",
    "subjectGroup": "제2외국어",
    "name": "베트남어 회화",
    "category": "진로 선택",
    "topics": [
      "상대의 말을 경청하며 적극적인 자세로 의사소통 활동에 참여한다.",
      "영역 01"
    ]
  },
  {
    "id": "kr.course.2022.high.a2f022fa12c0d889",
    "level": "high",
    "subjectGroup": "제2외국어",
    "name": "스페인어",
    "category": "공통",
    "topics": [
      "듣기",
      "말하기",
      "문화",
      "쓰기",
      "읽기"
    ]
  },
  {
    "id": "kr.course.2022.high.33db7f47c6543bd9",
    "level": "high",
    "subjectGroup": "제2외국어",
    "name": "스페인어 회화",
    "category": "진로 선택",
    "topics": [
      "스페인어로 의사소통하려는 적극적인 태도를 갖는다."
    ]
  },
  {
    "id": "kr.course.2022.high.a0ed3617828b3299",
    "level": "high",
    "subjectGroup": "제2외국어",
    "name": "스페인어권 문화",
    "category": "융합 선택",
    "topics": [
      "스페인어권 문화에 대한 이해를 바탕으로 타 문화에 대한 포용성과 문화적 감수성을 갖춘"
    ]
  },
  {
    "id": "kr.course.2022.high.a98a0804a4181a8f",
    "level": "high",
    "subjectGroup": "제2외국어",
    "name": "심화 독일어",
    "category": "공통",
    "topics": [
      "듣기",
      "말하기",
      "문화",
      "쓰기",
      "읽기"
    ]
  },
  {
    "id": "kr.course.2022.high.e37ee79cbe59c0f6",
    "level": "high",
    "subjectGroup": "제2외국어",
    "name": "심화 러시아어",
    "category": "공통",
    "topics": [
      "듣기",
      "말하기",
      "문화",
      "쓰기",
      "읽기"
    ]
  },
  {
    "id": "kr.course.2022.high.c7dc9c7786a8dd5f",
    "level": "high",
    "subjectGroup": "제2외국어",
    "name": "심화 베트남어",
    "category": "공통",
    "topics": [
      "듣기",
      "말하기",
      "문화",
      "쓰기",
      "읽기"
    ]
  },
  {
    "id": "kr.course.2022.high.ad744b150fe23529",
    "level": "high",
    "subjectGroup": "제2외국어",
    "name": "심화 스페인어",
    "category": "공통",
    "topics": [
      "듣기",
      "말하기",
      "문화",
      "쓰기",
      "읽기"
    ]
  },
  {
    "id": "kr.course.2022.high.2cb09eec65b781e4",
    "level": "high",
    "subjectGroup": "제2외국어",
    "name": "심화 아랍어",
    "category": "공통",
    "topics": [
      "듣기",
      "말하기",
      "문화",
      "쓰기",
      "읽기"
    ]
  },
  {
    "id": "kr.course.2022.high.d9daf47757b435b0",
    "level": "high",
    "subjectGroup": "제2외국어",
    "name": "심화 일본어",
    "category": "공통",
    "topics": [
      "듣기",
      "말하기",
      "문화",
      "쓰기",
      "읽기"
    ]
  },
  {
    "id": "kr.course.2022.high.f88260ffc472155f",
    "level": "high",
    "subjectGroup": "제2외국어",
    "name": "심화 중국어",
    "category": "공통",
    "topics": [
      "듣기",
      "말하기",
      "문화",
      "쓰기",
      "읽기"
    ]
  },
  {
    "id": "kr.course.2022.high.7c8d02894293899d",
    "level": "high",
    "subjectGroup": "제2외국어",
    "name": "심화 프랑스어",
    "category": "공통",
    "topics": [
      "듣기",
      "말하기",
      "문화",
      "쓰기",
      "읽기"
    ]
  },
  {
    "id": "kr.course.2022.high.4a17d7c173e709c4",
    "level": "high",
    "subjectGroup": "제2외국어",
    "name": "아랍 문화",
    "category": "융합 선택",
    "topics": [
      "아랍 문화와 일상생활에 대한 이해를 바탕으로 타 문화에 대한 포용성과 문화적 감수성을",
      "영역 01"
    ]
  },
  {
    "id": "kr.course.2022.high.e174321efa04422d",
    "level": "high",
    "subjectGroup": "제2외국어",
    "name": "아랍어",
    "category": "공통",
    "topics": [
      "듣기",
      "말하기",
      "문화",
      "쓰기",
      "읽기"
    ]
  },
  {
    "id": "kr.course.2022.high.0e0fde1c88540336",
    "level": "high",
    "subjectGroup": "제2외국어",
    "name": "아랍어 회화",
    "category": "진로 선택",
    "topics": [
      "상대방의 말을 경청하고 적극적인 자세로 의사소통 활동에 참여한다.",
      "영역 01"
    ]
  },
  {
    "id": "kr.course.2022.high.3ad829d8ba3c925b",
    "level": "high",
    "subjectGroup": "제2외국어",
    "name": "일본 문화",
    "category": "융합 선택",
    "topics": [
      "영역 01",
      "일본의 관심 분야에 대한 정보를 다양한 디지털 매체를 활용하여 조사하고, 상호 협력적"
    ]
  },
  {
    "id": "kr.course.2022.high.4e9088d831f0e0cd",
    "level": "high",
    "subjectGroup": "제2외국어",
    "name": "일본어",
    "category": "공통",
    "topics": [
      "듣기",
      "말하기",
      "문화",
      "쓰기",
      "읽기"
    ]
  },
  {
    "id": "kr.course.2022.high.72db3c865bea9cad",
    "level": "high",
    "subjectGroup": "제2외국어",
    "name": "일본어 회화",
    "category": "진로 선택",
    "topics": [
      "영역 01"
    ]
  },
  {
    "id": "kr.course.2022.high.c23016268b3a9190",
    "level": "high",
    "subjectGroup": "제2외국어",
    "name": "중국 문화",
    "category": "공통",
    "topics": [
      "영역 01",
      "중국 문화 중 관심 있는 분야의 정보를 다양한 매체를 통해 조사하고, 자신의 삶과 연계"
    ]
  },
  {
    "id": "kr.course.2022.high.570080530b122765",
    "level": "high",
    "subjectGroup": "제2외국어",
    "name": "중국어",
    "category": "공통",
    "topics": [
      "듣기",
      "말하기",
      "문화",
      "쓰기",
      "읽기"
    ]
  },
  {
    "id": "kr.course.2022.high.2bd78d4bae80b68c",
    "level": "high",
    "subjectGroup": "제2외국어",
    "name": "중국어 회화",
    "category": "진로 선택",
    "topics": [
      "영역 01",
      "중국어에 대한 관심과 호기심을 바탕으로 자신의 진로와 중국과의 연계성을 탐색한다."
    ]
  },
  {
    "id": "kr.course.2022.high.1701cc64d761d30c",
    "level": "high",
    "subjectGroup": "제2외국어",
    "name": "프랑스어",
    "category": "공통",
    "topics": [
      "듣기",
      "말하기",
      "문화",
      "쓰기",
      "읽기"
    ]
  },
  {
    "id": "kr.course.2022.high.26da649d802c8bc7",
    "level": "high",
    "subjectGroup": "제2외국어",
    "name": "프랑스어 회화",
    "category": "일반 선택",
    "topics": [
      "영역 01",
      "프랑스어권 구성원들과 적극적으로 의사소통하는 과정에서 상호 존중하고 협력하는 태도를"
    ]
  },
  {
    "id": "kr.course.2022.high.7343980bdac232d6",
    "level": "high",
    "subjectGroup": "제2외국어",
    "name": "프랑스어권 문화",
    "category": "공통",
    "topics": [
      "프랑스어권 구성원들과의 의사소통 상황에서 상호 존중하고 협력하는 태도를 기른다."
    ]
  },
  {
    "id": "kr.course.2022.high.f787bc1b3673c037",
    "level": "high",
    "subjectGroup": "체육",
    "name": "스포츠 과학",
    "category": "진로 선택",
    "topics": [
      "스포츠와 사회과학",
      "스포츠와 자연과학"
    ]
  },
  {
    "id": "kr.course.2022.high.7de8fa364f4ee2f0",
    "level": "high",
    "subjectGroup": "체육",
    "name": "스포츠 문화",
    "category": "진로 선택",
    "topics": [
      "스포츠 경기 문화",
      "스포츠 인문 문화"
    ]
  },
  {
    "id": "kr.course.2022.high.e651381ef9d478ba",
    "level": "high",
    "subjectGroup": "체육",
    "name": "스포츠 생활1",
    "category": "융합 선택",
    "topics": [
      "생활⋅자연환경형 스포츠",
      "영역형 스포츠"
    ]
  },
  {
    "id": "kr.course.2022.high.0bd4c56b6d8a1d04",
    "level": "high",
    "subjectGroup": "체육",
    "name": "스포츠 생활2",
    "category": "융합 선택",
    "topics": [
      "네트형 스포츠",
      "필드형 스포츠"
    ]
  },
  {
    "id": "kr.course.2022.high.039c51ec34c5e262",
    "level": "high",
    "subjectGroup": "체육",
    "name": "운동과 건강",
    "category": "진로 선택",
    "topics": [
      "건강 운동",
      "체력 운동"
    ]
  },
  {
    "id": "kr.course.2022.high.5ad7a1f55e918f4d",
    "level": "high",
    "subjectGroup": "체육",
    "name": "체육1",
    "category": "일반 선택",
    "topics": [
      "건강 관리",
      "생태형 스포츠",
      "전략형 스포츠"
    ]
  },
  {
    "id": "kr.course.2022.high.402672abea801ba4",
    "level": "high",
    "subjectGroup": "체육",
    "name": "체육2",
    "category": "일반 선택",
    "topics": [
      "기술형 스포츠",
      "체력 증진",
      "표현 활동"
    ]
  },
  {
    "id": "kr.course.2022.high.292f890cfcc63417",
    "level": "high",
    "subjectGroup": "체육 계열",
    "name": "고급 체육 전공 실기",
    "category": "진로 선택",
    "topics": [
      "응용 기능 트레이닝",
      "전공 실기 응용 기능"
    ]
  },
  {
    "id": "kr.course.2022.high.b1fea654f7356128",
    "level": "high",
    "subjectGroup": "체육 계열",
    "name": "기초 체육 전공 실기",
    "category": "진로 선택",
    "topics": [
      "기본 기능 트레이닝",
      "전공 실기 기본 기능"
    ]
  },
  {
    "id": "kr.course.2022.high.0e9793325ebd2eed",
    "level": "high",
    "subjectGroup": "체육 계열",
    "name": "수상 스포츠",
    "category": "진로 선택",
    "topics": [
      "수상 경기",
      "수상 스포츠 기술",
      "수상 스포츠와 사회"
    ]
  },
  {
    "id": "kr.course.2022.high.f454872043d8924b",
    "level": "high",
    "subjectGroup": "체육 계열",
    "name": "스포츠 개론",
    "category": "진로 선택",
    "topics": [
      "스포츠와 사회",
      "스포츠와 진로",
      "스포츠와 학문"
    ]
  },
  {
    "id": "kr.course.2022.high.ec65403336903281",
    "level": "high",
    "subjectGroup": "체육 계열",
    "name": "스포츠 경기 기술",
    "category": "진로 선택",
    "topics": [
      "경기 기술 트레이닝",
      "경기 기술과 전략",
      "스포츠 경기와 기술"
    ]
  },
  {
    "id": "kr.course.2022.high.4fd718da965f139b",
    "level": "high",
    "subjectGroup": "체육 계열",
    "name": "스포츠 경기 분석",
    "category": "진로 선택",
    "topics": [
      "경기 분석 방법",
      "경기 분석과 전략",
      "스포츠 경기와 분석"
    ]
  },
  {
    "id": "kr.course.2022.high.7c94e7bc8e6c1e94",
    "level": "high",
    "subjectGroup": "체육 계열",
    "name": "스포츠 경기 체력",
    "category": "진로 선택",
    "topics": [
      "경기 체력 트레이닝",
      "경기 체력의 관리",
      "스포츠 경기와 체력"
    ]
  },
  {
    "id": "kr.course.2022.high.67fa381458469390",
    "level": "high",
    "subjectGroup": "체육 계열",
    "name": "스포츠 교육",
    "category": "융합 선택",
    "topics": [
      "스포츠 교육과 진로",
      "스포츠 교육의 실제",
      "스포츠와 교육"
    ]
  },
  {
    "id": "kr.course.2022.high.dfa9fe34af45d7fe",
    "level": "high",
    "subjectGroup": "체육 계열",
    "name": "스포츠 생리의학",
    "category": "융합 선택",
    "topics": [
      "스포츠 생리의학과 진로",
      "스포츠 생리의학의 실제",
      "스포츠와 생리의학"
    ]
  },
  {
    "id": "kr.course.2022.high.79bd9cfacbebfc47",
    "level": "high",
    "subjectGroup": "체육 계열",
    "name": "스포츠 행정 및 경영",
    "category": "융합 선택",
    "topics": [
      "스포츠 행정 및 경영과 진로",
      "스포츠 행정 및 경영의 실제",
      "스포츠와 행정 및 경영"
    ]
  },
  {
    "id": "kr.course.2022.high.89cbeea5b619f291",
    "level": "high",
    "subjectGroup": "체육 계열",
    "name": "심화 체육 전공 실기",
    "category": "진로 선택",
    "topics": [
      "복합 기능 트레이닝",
      "전공 실기 복합 기능"
    ]
  },
  {
    "id": "kr.course.2022.high.7ad2cad46294c941",
    "level": "high",
    "subjectGroup": "체육 계열",
    "name": "육상",
    "category": "진로 선택",
    "topics": [
      "육상 경기",
      "육상 기술",
      "육상과 사회"
    ]
  },
  {
    "id": "kr.course.2022.high.a1421e3d62cd7dfe",
    "level": "high",
    "subjectGroup": "체육 계열",
    "name": "체조",
    "category": "진로 선택",
    "topics": [
      "체조 경기",
      "체조 기술",
      "체조와 사회"
    ]
  },
  {
    "id": "kr.course.2022.high.921a5aa050a7e8ed",
    "level": "high",
    "subjectGroup": "한문",
    "name": "언어생활과 한자",
    "category": "융합 선택",
    "topics": [
      "한자와 한자 어휘의 개념적 이해를 통해 추론적 사고를 할 수 있는 능력을 기른다."
    ]
  },
  {
    "id": "kr.course.2022.high.8a9d2db677d4856f",
    "level": "high",
    "subjectGroup": "한문",
    "name": "한문",
    "category": "일반 선택",
    "topics": [
      "문장",
      "한자와 어휘"
    ]
  },
  {
    "id": "kr.course.2022.high.9d8575499e88bf5d",
    "level": "high",
    "subjectGroup": "한문",
    "name": "한문 고전 읽기",
    "category": "진로 선택",
    "topics": [
      "한문으로 기록된 다양한 자료를 찾아 읽고 진로 탐색에 활용한다."
    ]
  },
  {
    "id": "kr.course.2022.middle.aaaae5ae7d8548a8",
    "level": "middle",
    "subjectGroup": "과학",
    "name": "과학",
    "category": "공통",
    "topics": [
      "과학과 나의 미래",
      "과학과 인류의 지속가능한 삶",
      "기체의 성질",
      "날씨와 기후변화",
      "동물과 에너지",
      "물질의 구성",
      "물질의 상태 변화",
      "물질의 특성",
      "별과 우주",
      "빛과 파동",
      "생물의 구성과 다양성",
      "생식과 유전",
      "수권과 해수의 순환",
      "식물과 에너지",
      "열",
      "운동과 에너지",
      "자극과 반응",
      "재해⋅재난과 안전",
      "전기와 자기",
      "지권의 변화",
      "태양계",
      "화학 반응의 규칙성",
      "힘의 작용"
    ]
  },
  {
    "id": "kr.course.2022.middle.a0f8efae1e2bd119",
    "level": "middle",
    "subjectGroup": "국어",
    "name": "국어",
    "category": "공통",
    "topics": [
      "듣기⋅말하기",
      "매체",
      "문법",
      "문학",
      "쓰기",
      "읽기"
    ]
  },
  {
    "id": "kr.course.2022.middle.92c889afa560b9d8",
    "level": "middle",
    "subjectGroup": "기술·가정/정보",
    "name": "기술·가정",
    "category": "공통",
    "topics": [
      "기술적 문제해결과 혁신",
      "생활환경과 지속가능한 선택",
      "인간 발달과 주도적 삶",
      "지속가능한 기술과 융합"
    ]
  },
  {
    "id": "kr.course.2022.middle.c197990b3a23fdd2",
    "level": "middle",
    "subjectGroup": "기술·가정/정보",
    "name": "정보",
    "category": "공통",
    "topics": [
      "데이터",
      "디지털 문화",
      "알고리즘과 프로그래밍",
      "인공지능",
      "컴퓨팅 시스템"
    ]
  },
  {
    "id": "kr.course.2022.middle.07f3bfc5942e5a74",
    "level": "middle",
    "subjectGroup": "도덕",
    "name": "도덕",
    "category": "공통",
    "topics": [
      "사회⋅공동체와의 관계",
      "자신과의 관계",
      "자연과의 관계",
      "타인과의 관계"
    ]
  },
  {
    "id": "kr.course.2022.middle.570335cd5c8192d8",
    "level": "middle",
    "subjectGroup": "미술",
    "name": "미술",
    "category": "공통",
    "topics": [
      "감상",
      "미적 체험",
      "표현"
    ]
  },
  {
    "id": "kr.course.2022.middle.dccd29079b173ca0",
    "level": "middle",
    "subjectGroup": "사회(역사 포함)",
    "name": "사회",
    "category": "공통",
    "topics": [
      "경제생활과 선택",
      "국제 사회와 한반도",
      "남부 지역",
      "다양한 문화의 이해",
      "대한민국, 우리가 살아가는 곳",
      "민주주의와 시민",
      "북부 지역",
      "사회 변동과 사회문제",
      "세계화 시대, 지리의 힘",
      "시장과 가격",
      "아메리카",
      "아시아",
      "아프리카",
      "오세아니아와 극지방",
      "우리나라 경제와 세계화",
      "우리나라의 자연환경과 인간 생활",
      "유럽",
      "인간과 사회생활",
      "인권과 기본권",
      "일상생활과 법",
      "정치과정과 시민 참여",
      "중부 지역",
      "지속가능한 세계와 글로컬 시민",
      "헌법과 국가기관"
    ]
  },
  {
    "id": "kr.course.2022.middle.718b305249a94a92",
    "level": "middle",
    "subjectGroup": "사회(역사 포함)",
    "name": "역사",
    "category": "공통",
    "topics": [
      "고려의 성립과 변천",
      "국가의 형성과 발전",
      "근⋅현대 사회로의 전환",
      "문명의 발생과 고대 세계의 형성",
      "세계 대전과 사회 변동",
      "세계 종교의 확산과 지역 문화의 발전",
      "역사 학습의 기초",
      "제국주의와 국민 국가 건설 운동",
      "조선 사회의 변동",
      "조선의 성립과 발전",
      "지역 세계의 교류와 변화",
      "통일신라와 발해",
      "현대 세계의 전개와 과제"
    ]
  },
  {
    "id": "kr.course.2022.middle.373e9959b3cc1af3",
    "level": "middle",
    "subjectGroup": "수학",
    "name": "수학",
    "category": "공통",
    "topics": [
      "도형과 측정",
      "변화와 관계",
      "수와 연산",
      "자료와 가능성"
    ]
  },
  {
    "id": "kr.course.2022.middle.fb948cdadbdc5da1",
    "level": "middle",
    "subjectGroup": "영어",
    "name": "영어",
    "category": "공통",
    "topics": [
      "이해",
      "표현"
    ]
  },
  {
    "id": "kr.course.2022.middle.b39f1ce9e94d344f",
    "level": "middle",
    "subjectGroup": "음악",
    "name": "음악",
    "category": "공통",
    "topics": [
      "감상",
      "연주",
      "창작"
    ]
  },
  {
    "id": "kr.course.2022.middle.66de94cebc86b61e",
    "level": "middle",
    "subjectGroup": "제2외국어",
    "name": "생활 독일어",
    "category": "중학교 선택",
    "topics": [
      "듣기",
      "말하기",
      "문화",
      "쓰기",
      "읽기"
    ]
  },
  {
    "id": "kr.course.2022.middle.2178b9d0de944d75",
    "level": "middle",
    "subjectGroup": "제2외국어",
    "name": "생활 러시아어",
    "category": "중학교 선택",
    "topics": [
      "듣기",
      "말하기",
      "문화",
      "쓰기",
      "읽기"
    ]
  },
  {
    "id": "kr.course.2022.middle.71b0ac4b7d3259ff",
    "level": "middle",
    "subjectGroup": "제2외국어",
    "name": "생활 베트남어",
    "category": "중학교 선택",
    "topics": [
      "듣기",
      "말하기",
      "문화",
      "쓰기",
      "읽기"
    ]
  },
  {
    "id": "kr.course.2022.middle.7b40e7aeddb08bc4",
    "level": "middle",
    "subjectGroup": "제2외국어",
    "name": "생활 스페인어",
    "category": "중학교 선택",
    "topics": [
      "듣기",
      "말하기",
      "문화",
      "쓰기",
      "읽기"
    ]
  },
  {
    "id": "kr.course.2022.middle.8783223c83ba74b3",
    "level": "middle",
    "subjectGroup": "제2외국어",
    "name": "생활 아랍어",
    "category": "중학교 선택",
    "topics": [
      "듣기",
      "말하기",
      "문화",
      "쓰기",
      "읽기"
    ]
  },
  {
    "id": "kr.course.2022.middle.91407698abb03db8",
    "level": "middle",
    "subjectGroup": "제2외국어",
    "name": "생활 일본어",
    "category": "중학교 선택",
    "topics": [
      "듣기",
      "말하기",
      "문화",
      "쓰기",
      "읽기"
    ]
  },
  {
    "id": "kr.course.2022.middle.19401e7f882c4108",
    "level": "middle",
    "subjectGroup": "제2외국어",
    "name": "생활 중국어",
    "category": "중학교 선택",
    "topics": [
      "듣기",
      "말하기",
      "문화",
      "쓰기",
      "읽기"
    ]
  },
  {
    "id": "kr.course.2022.middle.333940c638f6d1b2",
    "level": "middle",
    "subjectGroup": "제2외국어",
    "name": "생활 프랑스어",
    "category": "중학교 선택",
    "topics": [
      "듣기",
      "말하기",
      "문화",
      "쓰기",
      "읽기"
    ]
  },
  {
    "id": "kr.course.2022.middle.9cd4d075bde4ad85",
    "level": "middle",
    "subjectGroup": "중학교 선택",
    "name": "보건",
    "category": "중학교 선택",
    "topics": [
      "건강안전과 응급처치",
      "건강자원과 건강문화",
      "건강증진과 질병예방",
      "성과 건강",
      "정서와 정신건강"
    ]
  },
  {
    "id": "kr.course.2022.middle.4edb870c5459d216",
    "level": "middle",
    "subjectGroup": "중학교 선택",
    "name": "진로와 직업",
    "category": "중학교 선택",
    "topics": [
      "직업 세계와 진로 탐색",
      "진로 설계와 실천",
      "진로와 나의 이해"
    ]
  },
  {
    "id": "kr.course.2022.middle.ec48c1127e519a2e",
    "level": "middle",
    "subjectGroup": "중학교 선택",
    "name": "환경",
    "category": "중학교 선택",
    "topics": [
      "기후위기와 기후행동",
      "지속가능성과 시민 참여",
      "환경 문제와 쟁점",
      "환경 체계",
      "환경과 인간"
    ]
  },
  {
    "id": "kr.course.2022.middle.fa59961d660b0ad4",
    "level": "middle",
    "subjectGroup": "체육",
    "name": "체육",
    "category": "공통",
    "topics": [
      "스포츠",
      "운동",
      "표현"
    ]
  },
  {
    "id": "kr.course.2022.middle.43316f44a956438c",
    "level": "middle",
    "subjectGroup": "한문",
    "name": "한문",
    "category": "중학교 선택",
    "topics": [
      "문장",
      "한자와 어휘"
    ]
  }
];
